# Generated by Django 3.2.8 on 2021-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Python программист, iOS-разработчик, итд.', max_length=150, verbose_name='Название')),
                ('fullname', models.CharField(help_text='Иванов Иван', max_length=255, verbose_name='Фамилия и имя')),
                ('english', models.CharField(choices=[('0', 'Не знаю'), ('a1', 'A1 - Начальный уровень'), ('a2', 'A2 - Элементарный уровень '), ('b1', 'B1 - Средний уровень'), ('b2', 'B2 - Средне-продвинутый уровень'), ('c1', 'C1 - Продвинутый уровень '), ('c2', 'C2 - Владение в совершенств')], max_length=2, verbose_name='Владение английским')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, help_text='Ссылка на профиль, пример: linkedin.com/in/you_name')),
                ('github', models.URLField(blank=True, help_text='Ссылка на профиль, пример: github.com/you_name')),
                ('contact', models.CharField(help_text='Предпочитаемый способ связи (емайл, линкендин, телеграмм и т.п.)', max_length=100, verbose_name='Контакт')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('skills', models.TextField(help_text='Знаю React.js, пользуюсь Vim, Работал с AWS', max_length=1000, verbose_name='Навыки')),
                ('awards', models.TextField(blank=True, help_text='Участие в олимпиадах, хакатонах, других профильных меропритиях. Курсы.', max_length=1000, verbose_name='Награды, сертификаты')),
            ],
        ),
    ]
