# Generated by Django 3.2.8 on 2021-10-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(blank=True, help_text='Специальность, учебное заведение', max_length=255, null=True, verbose_name='Описание')),
                ('education_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('education_end', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('studying_now', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('work_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должнолсть')),
                ('work_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('work_end', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('work_now', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Обязанности, достижения', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cv.education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cv.workexperience'),
        ),
    ]
