# Generated by Django 3.2.8 on 2021-10-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cv', '0002_auto_20211025_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu', to='app_cv.education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='app_cv.workexperience'),
        ),
    ]
