# Generated by Django 3.2.8 on 2021-10-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cv', '0003_auto_20211026_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cv.cv'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cv.cv'),
        ),
    ]
