# Generated by Django 3.2.8 on 2021-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cv', '0006_auto_20211026_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ManyToManyField(blank=True, to='app_cv.Education'),
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='cv',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='app_cv.WorkExperience'),
        ),
    ]
